// Generated by commsdsl2comms v7.0.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::message::Gwinfo message and its fields.

#pragma once

#include "cc_mqttsn/field/GwAddCommon.h"
#include "cc_mqttsn/field/GwIdCommon.h"

namespace cc_mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqttsn::message::Gwinfo message.
/// @see cc_mqttsn::message::GwinfoFields
struct GwinfoFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::GwinfoFields::GwId field.
    using GwIdCommon = cc_mqttsn::field::GwIdCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::GwinfoFields::GwAdd field.
    using GwAddCommon = cc_mqttsn::field::GwAddCommon;
};

/// @brief Common types and functions of 
///     @ref cc_mqttsn::message::Gwinfo message.
struct GwinfoCommon
{
    /// @brief Name of the @ref cc_mqttsn::message::Gwinfo message.
    static const char* name()
    {
        return "GWINFO";
    }
};

} // namespace message

} // namespace cc_mqttsn
