// Generated by commsdsl2comms v5.2.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::message::Pingresp message and its fields.

#pragma once

namespace cc_mqttsn
{

namespace message
{

/// @brief Common types and functions of 
///     @ref cc_mqttsn::message::Pingresp message.
struct PingrespCommon
{
    /// @brief Name of the @ref cc_mqttsn::message::Pingresp message.
    static const char* name()
    {
        return "PINGRESP";
    }
};

} // namespace message

} // namespace cc_mqttsn
