// Generated by commsdsl2comms v7.1.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::message::Publish message and its fields.

#pragma once

#include "cc_mqttsn/field/DataCommon.h"
#include "cc_mqttsn/field/FlagsCommon.h"
#include "cc_mqttsn/field/MessageIdCommon.h"
#include "cc_mqttsn/field/TopicIdCommon.h"

namespace cc_mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqttsn::message::Publish message.
/// @see cc_mqttsn::message::PublishFields
struct PublishFieldsCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref cc_mqttsn::message::PublishFields::Flags field.
    using FlagsMembersCommon = cc_mqttsn::field::FlagsMembersCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::PublishFields::Flags field.
    using FlagsCommon = cc_mqttsn::field::FlagsCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::PublishFields::TopicId field.
    using TopicIdCommon = cc_mqttsn::field::TopicIdCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::PublishFields::MsgId field.
    using MsgIdCommon = cc_mqttsn::field::MessageIdCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::PublishFields::Data field.
    using DataCommon = cc_mqttsn::field::DataCommon;
};

/// @brief Common types and functions of 
///     @ref cc_mqttsn::message::Publish message.
struct PublishCommon
{
    /// @brief Name of the @ref cc_mqttsn::message::Publish message.
    static const char* name()
    {
        return "PUBLISH";
    }
};

} // namespace message

} // namespace cc_mqttsn
