// Generated by commsdsl2comms v5.1.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::message::Regack message and its fields.

#pragma once

#include "cc_mqttsn/field/MessageIdCommon.h"
#include "cc_mqttsn/field/ReturnCodeCommon.h"
#include "cc_mqttsn/field/TopicIdCommon.h"

namespace cc_mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqttsn::message::Regack message.
/// @see cc_mqttsn::message::RegackFields
struct RegackFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::RegackFields::TopicId field.
    using TopicIdCommon = cc_mqttsn::field::TopicIdCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::RegackFields::MsgId field.
    using MsgIdCommon = cc_mqttsn::field::MessageIdCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::RegackFields::ReturnCode field.
    using ReturnCodeCommon = cc_mqttsn::field::ReturnCodeCommon;
};

/// @brief Common types and functions of 
///     @ref cc_mqttsn::message::Regack message.
struct RegackCommon
{
    /// @brief Name of the @ref cc_mqttsn::message::Regack message.
    static const char* name()
    {
        return "REGACK";
    }
};

} // namespace message

} // namespace cc_mqttsn
