// Generated by commsdsl2comms v6.3.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::message::Register message and its fields.

#pragma once

#include "cc_mqttsn/field/MessageIdCommon.h"
#include "cc_mqttsn/field/TopicIdCommon.h"
#include "cc_mqttsn/field/TopicNameCommon.h"

namespace cc_mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqttsn::message::Register message.
/// @see cc_mqttsn::message::RegisterFields
struct RegisterFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::RegisterFields::TopicId field.
    using TopicIdCommon = cc_mqttsn::field::TopicIdCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::RegisterFields::MsgId field.
    using MsgIdCommon = cc_mqttsn::field::MessageIdCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::RegisterFields::TopicName field.
    using TopicNameCommon = cc_mqttsn::field::TopicNameCommon;
};

/// @brief Common types and functions of 
///     @ref cc_mqttsn::message::Register message.
struct RegisterCommon
{
    /// @brief Name of the @ref cc_mqttsn::message::Register message.
    static const char* name()
    {
        return "REGISTER";
    }
};

} // namespace message

} // namespace cc_mqttsn
