// Generated by commsdsl2comms v5.1.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::message::Willmsgreq message and its fields.

#pragma once

namespace cc_mqttsn
{

namespace message
{

/// @brief Common types and functions of 
///     @ref cc_mqttsn::message::Willmsgreq message.
struct WillmsgreqCommon
{
    /// @brief Name of the @ref cc_mqttsn::message::Willmsgreq message.
    static const char* name()
    {
        return "WILLMSGREQ";
    }
};

} // namespace message

} // namespace cc_mqttsn
