// Generated by commsdsl2comms v7.0.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::message::Willtopicresp message and its fields.

#pragma once

#include "cc_mqttsn/field/ReturnCodeCommon.h"

namespace cc_mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqttsn::message::Willtopicresp message.
/// @see cc_mqttsn::message::WilltopicrespFields
struct WilltopicrespFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_mqttsn::message::WilltopicrespFields::ReturnCode field.
    using ReturnCodeCommon = cc_mqttsn::field::ReturnCodeCommon;
};

/// @brief Common types and functions of 
///     @ref cc_mqttsn::message::Willtopicresp message.
struct WilltopicrespCommon
{
    /// @brief Name of the @ref cc_mqttsn::message::Willtopicresp message.
    static const char* name()
    {
        return "WILLTOPICRESP";
    }
};

} // namespace message

} // namespace cc_mqttsn
