// Generated by commsdsl2comms v8.1.0

/// @file
/// @brief Contains definition of message ids enumeration.

#pragma once

#include <cstdint>
#include "cc_mqttsn/Version.h"

namespace cc_mqttsn
{

/// @brief Message ids enumeration.
enum MsgId : std::uint8_t
{
    MsgId_Advertise = 0x00, ///< message id of <b>ADVERTISE</b> message. 
    MsgId_Searchgw = 0x01, ///< message id of <b>SEARCHGW</b> message. 
    MsgId_Gwinfo = 0x02, ///< message id of <b>GWINFO</b> message. 
    MsgId_Connect = 0x04, ///< message id of <b>CONNECT</b> message. 
    MsgId_Connack = 0x05, ///< message id of <b>CONNACK</b> message. 
    MsgId_Willtopicreq = 0x06, ///< message id of <b>WILLTOPICREQ</b> message. 
    MsgId_Willtopic = 0x07, ///< message id of <b>WILLTOPIC</b> message. 
    MsgId_Willmsgreq = 0x08, ///< message id of <b>WILLMSGREQ</b> message. 
    MsgId_Willmsg = 0x09, ///< message id of <b>WILLMSG</b> message. 
    MsgId_Register = 0x0A, ///< message id of <b>REGISTER</b> message. 
    MsgId_Regack = 0x0B, ///< message id of <b>REGACK</b> message. 
    MsgId_Publish = 0x0C, ///< message id of <b>PUBLISH</b> message. 
    MsgId_Puback = 0x0D, ///< message id of <b>PUBACK</b> message. 
    MsgId_Pubcomp = 0x0E, ///< message id of <b>PUBCOMP</b> message. 
    MsgId_Pubrec = 0x0F, ///< message id of <b>PUBREC</b> message. 
    MsgId_Pubrel = 0x10, ///< message id of <b>PUBREL</b> message. 
    MsgId_Subscribe = 0x12, ///< message id of <b>SUBSCRIBE</b> message. 
    MsgId_Suback = 0x13, ///< message id of <b>SUBACK</b> message. 
    MsgId_Unsubscribe = 0x14, ///< message id of <b>UNSUBSCRIBE</b> message. 
    MsgId_Unsuback = 0x15, ///< message id of <b>UNSUBACK</b> message. 
    MsgId_Pingreq = 0x16, ///< message id of <b>PINGREQ</b> message. 
    MsgId_Pingresp = 0x17, ///< message id of <b>PINGRESP</b> message. 
    MsgId_Disconnect = 0x18, ///< message id of <b>DISCONNECT</b> message. 
    MsgId_Willtopicupd = 0x1A, ///< message id of <b>WILLTOPICUPD</b> message. 
    MsgId_Willtopicresp = 0x1B, ///< message id of <b>WILLTOPICRESP</b> message. 
    MsgId_Willmsgupd = 0x1C, ///< message id of <b>WILLMSGUPD</b> message. 
    MsgId_Willmsgresp = 0x1D, ///< message id of <b>WILLMSGRESP</b> message. 
    MsgId_Fwd = 0xFE, ///< message id of <b>FWD</b> message. 

    // --- Extra values generated for convenience ---
    MsgId_FirstValue = 0x00, ///< First defined value.
    MsgId_LastValue = 0xFE, ///< Last defined value.
    MsgId_ValuesLimit = 0xFF, ///< Upper limit for defined values.
};

} // namespace cc_mqttsn
