// Generated by commsdsl2comms v3.3.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::message::Willtopic message and its fields.

#pragma once

#include "mqttsn/field/FlagsCommon.h"
#include "mqttsn/field/WillTopicCommon.h"

namespace mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref mqttsn::message::Willtopic message.
/// @see mqttsn::message::WilltopicFields
struct WilltopicFieldsCommon
{
    /// @brief Common types and functions for members of
    ///     @ref mqttsn::message::WilltopicFields::Flags field.
    using FlagsMembersCommon = mqttsn::field::FlagsMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqttsn::message::WilltopicFields::Flags field.
    using FlagsCommon = mqttsn::field::FlagsCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqttsn::message::WilltopicFields::WillTopic field.
    using WillTopicCommon = mqttsn::field::WillTopicCommon;
    
};

/// @brief Common types and functions of 
///     @ref mqttsn::message::Willtopic message.
/// @see mqttsn::message::Willtopic
struct WilltopicCommon
{
    /// @brief Name of the @ref mqttsn::message::Willtopic message.
    static const char* name()
    {
        return "WILLTOPIC";
    }
    
};

} // namespace message

} // namespace mqttsn


