// Generated by commsdsl2comms v3.3.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::message::Willtopicupd message and its fields.

#pragma once

#include "mqttsn/field/WillTopicCommon.h"

namespace mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref mqttsn::message::Willtopicupd message.
/// @see mqttsn::message::WilltopicupdFields
struct WilltopicupdFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqttsn::message::WilltopicupdFields::WillTopic field.
    using WillTopicCommon = mqttsn::field::WillTopicCommon;
    
};

/// @brief Common types and functions of 
///     @ref mqttsn::message::Willtopicupd message.
/// @see mqttsn::message::Willtopicupd
struct WilltopicupdCommon
{
    /// @brief Name of the @ref mqttsn::message::Willtopicupd message.
    static const char* name()
    {
        return "WILLTOPICUPD";
    }
    
};

} // namespace message

} // namespace mqttsn


