// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::message::Willtopicreq message and its fields.

#pragma once

namespace mqttsn
{

namespace message
{

/// @brief Common types and functions of 
///     @ref mqttsn::message::Willtopicreq message.
struct WilltopicreqCommon
{
    /// @brief Name of the @ref mqttsn::message::Willtopicreq message.
    static const char* name()
    {
        return "WILLTOPICREQ";
    }
};

} // namespace message

} // namespace mqttsn
