// Generated by commsdsl2comms v7.1.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::field::ClientId field.

#pragma once

namespace cc_mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqttsn::field::ClientId field.
struct ClientIdCommon
{
    /// @brief Name of the @ref cc_mqttsn::field::ClientId field.
    static const char* name()
    {
        return "ClientId";
    }
};

} // namespace field

} // namespace cc_mqttsn
