// Generated by commsdsl2comms v7.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::field::Data field.

#pragma once

namespace cc_mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqttsn::field::Data field.
struct DataCommon
{
    /// @brief Name of the @ref cc_mqttsn::field::Data field.
    static const char* name()
    {
        return "Data";
    }
};

} // namespace field

} // namespace cc_mqttsn
