// Generated by commsdsl2comms v6.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::field::GwAdd field.

#pragma once

namespace cc_mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqttsn::field::GwAdd field.
struct GwAddCommon
{
    /// @brief Name of the @ref cc_mqttsn::field::GwAdd field.
    static const char* name()
    {
        return "GwAdd";
    }
};

} // namespace field

} // namespace cc_mqttsn
