// Generated by commsdsl2comms v7.0.3

/// @file
/// @brief Contains definition of <b>"NodeId"</b> field.

#pragma once

#include <cstdint>
#include "cc_mqttsn/field/FieldBase.h"
#include "cc_mqttsn/field/NodeIdCommon.h"
#include "cc_mqttsn/options/DefaultOptions.h"
#include "comms/field/ArrayList.h"
#include "comms/options.h"

namespace cc_mqttsn
{

namespace field
{

/// @brief Definition of <b>"NodeId"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = cc_mqttsn::options::DefaultOptions, typename... TExtraOpts>
class NodeId : public
    comms::field::ArrayList<
        cc_mqttsn::field::FieldBase<>,
        std::uint8_t,
        TExtraOpts...,
        typename TOpt::field::NodeId,
        comms::option::def::HasName
    >
{
    using Base =
        comms::field::ArrayList<
            cc_mqttsn::field::FieldBase<>,
            std::uint8_t,
            TExtraOpts...,
            typename TOpt::field::NodeId,
            comms::option::def::HasName
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return cc_mqttsn::field::NodeIdCommon::name();
    }
};

} // namespace field

} // namespace cc_mqttsn
