// Generated by commsdsl2comms v7.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::field::NodeId field.

#pragma once

namespace cc_mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqttsn::field::NodeId field.
struct NodeIdCommon
{
    /// @brief Name of the @ref cc_mqttsn::field::NodeId field.
    static const char* name()
    {
        return "NodeId";
    }
};

} // namespace field

} // namespace cc_mqttsn
