// Generated by commsdsl2comms v7.0.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::field::TopicName field.

#pragma once

namespace cc_mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqttsn::field::TopicName field.
struct TopicNameCommon
{
    /// @brief Name of the @ref cc_mqttsn::field::TopicName field.
    static const char* name()
    {
        return "TopicName";
    }
};

} // namespace field

} // namespace cc_mqttsn
