// Generated by commsdsl2comms v6.3.4

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::field::WillMsg field.

#pragma once

namespace cc_mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqttsn::field::WillMsg field.
struct WillMsgCommon
{
    /// @brief Name of the @ref cc_mqttsn::field::WillMsg field.
    static const char* name()
    {
        return "WillMsg";
    }
};

} // namespace field

} // namespace cc_mqttsn
