// Generated by commsdsl2comms v6.2.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqttsn::field::WillTopic field.

#pragma once

namespace cc_mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqttsn::field::WillTopic field.
struct WillTopicCommon
{
    /// @brief Name of the @ref cc_mqttsn::field::WillTopic field.
    static const char* name()
    {
        return "WillTopic";
    }
};

} // namespace field

} // namespace cc_mqttsn
