// Generated by commsdsl2comms v6.0.0

/// @file
/// @brief Contains definition of protocol default options.

#pragma once

#include "comms/options.h"

namespace cc_mqttsn
{

namespace options
{

/// @brief Empty class to serve as the base for options.
struct EmptyOptions {};

/// @brief Default (empty) options of the protocol.
template <typename TBase = EmptyOptions>
struct DefaultOptionsT : public TBase
{
    /// @brief Extra options for fields.
    struct field
    {
        /// @brief Extra options for @ref
        ///     cc_mqttsn::field::ClientId field.
        using ClientId = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::field::Data field.
        using Data = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::field::GwAdd field.
        using GwAdd = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::field::TopicName field.
        using TopicName = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::field::WillMsg field.
        using WillMsg = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::field::WillTopic field.
        using WillTopic = comms::option::EmptyOption;
    }; // struct field

    /// @brief Extra options for messages.
    struct message
    {
        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Advertise message.
        using Advertise = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Connack message.
        using Connack = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Connect message.
        using Connect = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Searchgw message.
        using Searchgw = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Suback message.
        using Suback = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Subscribe message.
        using Subscribe = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Unsuback message.
        using Unsuback = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Unsubscribe message.
        using Unsubscribe = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Willmsg message.
        using Willmsg = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Willmsgreq message.
        using Willmsgreq = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Willmsgresp message.
        using Willmsgresp = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Willmsgupd message.
        using Willmsgupd = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Willtopic message.
        using Willtopic = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Willtopicreq
        ///     message.
        using Willtopicreq = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Willtopicresp
        ///     message.
        using Willtopicresp = comms::option::EmptyOption;

        /// @brief Extra options for @ref
        ///     cc_mqttsn::message::Willtopicupd
        ///     message.
        using Willtopicupd = comms::option::EmptyOption;
    }; // struct message

    /// @brief Extra options for frames.
    struct frame
    {
        /// @brief Extra options for layers of
        ///     @ref cc_mqttsn::frame::Frame frame.
        struct FrameLayers
        {
            /// @brief Extra options for @ref
            ///     cc_mqttsn::frame::FrameLayers::Data
            ///     layer.
            using Data = comms::option::EmptyOption;

            /// @brief Extra options for @ref
            ///     cc_mqttsn::frame::FrameLayers::Id layer.
            using Id = comms::option::EmptyOption;
        }; // struct FrameLayers
    }; // struct frame
};

/// @brief Default (empty) options of the protocol.
using DefaultOptions = DefaultOptionsT<>;

} // namespace options

} // namespace cc_mqttsn
