// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::field::ClientId field.

#pragma once

namespace mqttsn
{

namespace field
{


/// @brief Common types and functions for
///     @ref mqttsn::field::ClientId field.
struct ClientIdCommon
{
    /// @brief Name of the @ref mqttsn::field::ClientId field.
    static const char* name()
    {
        return "ClientId";
    }
    
};

} // namespace field

} // namespace mqttsn

