// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::field::Flags field.

#pragma once

#include <type_traits>
#include "mqttsn/field/QosCommon.h"
#include "mqttsn/field/TopicIdTypeCommon.h"

namespace mqttsn
{

namespace field
{

/// @brief Scope for all the common definitions of the member fields of
///     @ref mqttsn::field::Flags field.
struct FlagsMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref mqttsn::field::FlagsMembers::TopicIdType field.
    using TopicIdTypeCommon = mqttsn::field::TopicIdTypeCommon;

    /// @brief Common types and functions for
    ///     @ref mqttsn::field::FlagsMembers::Mid field.
    struct MidCommon
    {
        /// @brief Name of the @ref mqttsn::field::FlagsMembers::Mid field.
        static const char* name()
        {
            return "";
        }

        /// @brief Retrieve name of the bit of
        ///     @ref mqttsn::field::FlagsMembers::Mid field.
        static const char* bitName(std::size_t idx)
        {
            static const char* Map[] = {
                "CleanSession",
                "Will",
                "Retain"
            };

            static const std::size_t MapSize = std::extent<decltype(Map)>::value;
            if (MapSize <= idx) {
                return nullptr;
            }

            return Map[idx];
        }
    };

    /// @brief Common types and functions for
    ///     @ref mqttsn::field::FlagsMembers::Qos field.
    using QosCommon = mqttsn::field::QosCommon;

    /// @brief Common types and functions for
    ///     @ref mqttsn::field::FlagsMembers::High field.
    struct HighCommon
    {
        /// @brief Name of the @ref mqttsn::field::FlagsMembers::High field.
        static const char* name()
        {
            return "";
        }

        /// @brief Retrieve name of the bit of
        ///     @ref mqttsn::field::FlagsMembers::High field.
        static const char* bitName(std::size_t idx)
        {
            static const char* Map[] = {
                "Dup"
            };

            static const std::size_t MapSize = std::extent<decltype(Map)>::value;
            if (MapSize <= idx) {
                return nullptr;
            }

            return Map[idx];
        }
    };
};

/// @brief Common types and functions for
///     @ref mqttsn::field::Flags field.
struct FlagsCommon
{
    /// @brief Name of the @ref mqttsn::field::Flags field.
    static const char* name()
    {
        return "Flags";
    }
};

} // namespace field

} // namespace mqttsn
