// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::field::GwAdd field.

#pragma once

namespace mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref mqttsn::field::GwAdd field.
struct GwAddCommon
{
    /// @brief Name of the @ref mqttsn::field::GwAdd field.
    static const char* name()
    {
        return "GwAdd";
    }
};

} // namespace field

} // namespace mqttsn
