// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"MsgId"</b> field.

#pragma once

#include "comms/field/EnumValue.h"
#include "comms/options.h"
#include "mqttsn/field/FieldBase.h"
#include "mqttsn/field/MsgIdCommon.h"
#include "mqttsn/options/DefaultOptions.h"

namespace mqttsn
{

namespace field
{


/// @brief Definition of <b>"MsgId"</b> field.
/// @see @ref mqttsn::MsgId
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqttsn::options::DefaultOptions, typename... TExtraOpts>
class MsgId : public
    comms::field::EnumValue<
        mqttsn::field::FieldBase<>,
        mqttsn::field::MsgIdCommon::ValueType,
        TExtraOpts...,
        comms::option::def::ValidNumValueRange<0, 2>,
        comms::option::def::ValidNumValueRange<4, 16>,
        comms::option::def::ValidNumValueRange<18, 24>,
        comms::option::def::ValidNumValueRange<26, 29>
    >
{
    using Base =
        comms::field::EnumValue<
            mqttsn::field::FieldBase<>,
            mqttsn::field::MsgIdCommon::ValueType,
            TExtraOpts...,
            comms::option::def::ValidNumValueRange<0, 2>,
            comms::option::def::ValidNumValueRange<4, 16>,
            comms::option::def::ValidNumValueRange<18, 24>,
            comms::option::def::ValidNumValueRange<26, 29>
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;
    
    /// @brief Single value name info entry.
    using ValueNameInfo = mqttsn::field::MsgIdCommon::ValueNameInfo;
    
    /// @brief Type returned from @ref valueNamesMap() member function.
    /// @see @ref mqttsn::field::MsgIdCommon::ValueNamesMapInfo.
    using ValueNamesMapInfo = mqttsn::field::MsgIdCommon::ValueNamesMapInfo;
    
    /// @brief Retrieve name of the enum value.
    /// @see @ref mqttsn::field::MsgIdCommon::valueName().
    static const char* valueName(ValueType val)
    {
        return mqttsn::field::MsgIdCommon::valueName(val);
    }
    
    /// @brief Retrieve name of the @b current value
    const char* valueName() const
    {
        return valueName(Base::value());
    }
    
    /// @brief Retrieve map of enum value names.
    /// @see @ref mqttsn::field::MsgIdCommon::valueNamesMap().
    static ValueNamesMapInfo valueNamesMap()
    {
        return mqttsn::field::MsgIdCommon::valueNamesMap();
    }
    
    
    /// @brief Name of the field.
    static const char* name()
    {
        return mqttsn::field::MsgIdCommon::name();
    }
    

};


} // namespace field

} // namespace mqttsn

