// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"ReturnCode"</b> field.

#pragma once

#include "comms/field/EnumValue.h"
#include "comms/options.h"
#include "mqttsn/field/FieldBase.h"
#include "mqttsn/field/ReturnCodeCommon.h"
#include "mqttsn/options/DefaultOptions.h"

namespace mqttsn
{

namespace field
{


/// @brief Definition of <b>"ReturnCode"</b> field.
/// @see @ref mqttsn::field::ReturnCodeCommon::ValueType
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqttsn::options::DefaultOptions, typename... TExtraOpts>
class ReturnCode : public
    comms::field::EnumValue<
        mqttsn::field::FieldBase<>,
        mqttsn::field::ReturnCodeCommon::ValueType,
        TExtraOpts...,
        comms::option::def::ValidNumValueRange<0, 3>
    >
{
    using Base =
        comms::field::EnumValue<
            mqttsn::field::FieldBase<>,
            mqttsn::field::ReturnCodeCommon::ValueType,
            TExtraOpts...,
            comms::option::def::ValidNumValueRange<0, 3>
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;
    
    /// @brief Single value name info entry.
    using ValueNameInfo = mqttsn::field::ReturnCodeCommon::ValueNameInfo;
    
    /// @brief Type returned from @ref valueNamesMap() member function.
    /// @see @ref mqttsn::field::ReturnCodeCommon::ValueNamesMapInfo.
    using ValueNamesMapInfo = mqttsn::field::ReturnCodeCommon::ValueNamesMapInfo;
    
    /// @brief Retrieve name of the enum value.
    /// @see @ref mqttsn::field::ReturnCodeCommon::valueName().
    static const char* valueName(ValueType val)
    {
        return mqttsn::field::ReturnCodeCommon::valueName(val);
    }
    
    /// @brief Retrieve name of the @b current value
    const char* valueName() const
    {
        return valueName(Base::value());
    }
    
    /// @brief Retrieve map of enum value names.
    /// @see @ref mqttsn::field::ReturnCodeCommon::valueNamesMap().
    static ValueNamesMapInfo valueNamesMap()
    {
        return mqttsn::field::ReturnCodeCommon::valueNamesMap();
    }
    
    
    /// @brief Name of the field.
    static const char* name()
    {
        return mqttsn::field::ReturnCodeCommon::name();
    }
    

};


} // namespace field

} // namespace mqttsn

