// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains definition of <b>"TopicIdType"</b> field.

#pragma once

#include "comms/field/EnumValue.h"
#include "comms/options.h"
#include "mqttsn/field/FieldBase.h"
#include "mqttsn/field/TopicIdTypeCommon.h"
#include "mqttsn/options/DefaultOptions.h"

namespace mqttsn
{

namespace field
{

/// @brief Definition of <b>"TopicIdType"</b> field.
/// @see @ref mqttsn::field::TopicIdTypeCommon::ValueType
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqttsn::options::DefaultOptions, typename... TExtraOpts>
class TopicIdType : public
    comms::field::EnumValue<
        mqttsn::field::FieldBase<>,
        mqttsn::field::TopicIdTypeCommon::ValueType,
        TExtraOpts...,
        comms::option::def::ValidNumValueRange<0, 2>
    >
{
    using Base =
        comms::field::EnumValue<
            mqttsn::field::FieldBase<>,
            mqttsn::field::TopicIdTypeCommon::ValueType,
            TExtraOpts...,
            comms::option::def::ValidNumValueRange<0, 2>
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;

    /// @brief Single value name info entry.
    using ValueNameInfo = mqttsn::field::TopicIdTypeCommon::ValueNameInfo;

    /// @brief Type returned from @ref valueNamesMap() member function.
    /// @see @ref mqttsn::field::TopicIdTypeCommon::ValueNamesMapInfo.
    using ValueNamesMapInfo = mqttsn::field::TopicIdTypeCommon::ValueNamesMapInfo;

    /// @brief Retrieve name of the enum value.
    /// @see @ref mqttsn::field::TopicIdTypeCommon::valueName().
    static const char* valueName(ValueType val)
    {
        return mqttsn::field::TopicIdTypeCommon::valueName(val);
    }

    /// @brief Retrieve name of the @b current value
    const char* valueName() const
    {
        return valueName(Base::getValue());
    }

    /// @brief Retrieve map of enum value names.
    /// @see @ref mqttsn::field::TopicIdTypeCommon::valueNamesMap().
    static ValueNamesMapInfo valueNamesMap()
    {
        return mqttsn::field::TopicIdTypeCommon::valueNamesMap();
    }

    /// @brief Name of the field.
    static const char* name()
    {
        return mqttsn::field::TopicIdTypeCommon::name();
    }
};

} // namespace field

} // namespace mqttsn
