// Generated by commsdsl2comms v7.1.0

/// @file
/// @brief Contains dispatch to handling function(s) for Gw platform server input input messages.

#pragma once

#include <cstdint>
#include "cc_mqttsn/input/GwServerInputMessages.h"
#include "cc_mqttsn/options/DefaultOptions.h"

namespace cc_mqttsn
{

namespace dispatch
{

/// @brief Dispatch message object to its appropriate handling function.
/// @details @b switch statement based (on message ID) cast and dispatch functionality.
/// @tparam TProtOptions Protocol options struct used for the application,
///     like @ref cc_mqttsn::options::DefaultOptions.
/// @param[in] id Numeric message ID.
/// @param[in] msg Message object held by reference to its interface class.
/// @param[in] handler Reference to handling object. Must define
///     @b handle() member function for every message type it exects
///     to handle and one for the interface class as well.
///     @code
///     using MyInterface = cc_mqttsn::Message<...>;
///     using MySearchgw = cc_mqttsn::message::Searchgw<MyInterface, cc_mqttsn::options::DefaultOptions>;
///     using MyGwinfo = cc_mqttsn::message::Gwinfo<MyInterface, cc_mqttsn::options::DefaultOptions>;
///     struct MyHandler {
///         void handle(MySearchgw& msg) {...}
///         void handle(MyGwinfo& msg) {...}
///         ...
///         // Handle all unexpected or irrelevant messages.
///         void handle(MyInterface& msg) {...}
///     };
///     @endcode
///     Every @b handle() function may return a value, but every
///     function must return the @b same type.
/// @note Defined in cc_mqttsn/dispatch/DispatchGwServerInputMessage.h
template<typename TProtOptions, typename TId, typename TMsg, typename THandler>
auto dispatchGwServerInputMessage(
    TId id,
    TMsg& msg,
    THandler& handler) -> decltype(handler.handle(msg))
{
    using InterfaceType = typename std::decay<decltype(msg)>::type;
    switch(static_cast<std::intmax_t>(id)) {
    case 1 /* 0x1 */:
    {
        using MsgType = cc_mqttsn::message::Searchgw<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 2 /* 0x2 */:
    {
        using MsgType = cc_mqttsn::message::Gwinfo<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 4 /* 0x4 */:
    {
        using MsgType = cc_mqttsn::message::Connect<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 7 /* 0x7 */:
    {
        using MsgType = cc_mqttsn::message::Willtopic<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 9 /* 0x9 */:
    {
        using MsgType = cc_mqttsn::message::Willmsg<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 10 /* 0xa */:
    {
        using MsgType = cc_mqttsn::message::Register<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 11 /* 0xb */:
    {
        using MsgType = cc_mqttsn::message::Regack<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 12 /* 0xc */:
    {
        using MsgType = cc_mqttsn::message::Publish<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 13 /* 0xd */:
    {
        using MsgType = cc_mqttsn::message::Puback<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 14 /* 0xe */:
    {
        using MsgType = cc_mqttsn::message::Pubcomp<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 15 /* 0xf */:
    {
        using MsgType = cc_mqttsn::message::Pubrec<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 16 /* 0x10 */:
    {
        using MsgType = cc_mqttsn::message::Pubrel<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 18 /* 0x12 */:
    {
        using MsgType = cc_mqttsn::message::Subscribe<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 20 /* 0x14 */:
    {
        using MsgType = cc_mqttsn::message::Unsubscribe<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 22 /* 0x16 */:
    {
        using MsgType = cc_mqttsn::message::Pingreq<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 23 /* 0x17 */:
    {
        using MsgType = cc_mqttsn::message::Pingresp<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 24 /* 0x18 */:
    {
        using MsgType = cc_mqttsn::message::Disconnect<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 26 /* 0x1a */:
    {
        using MsgType = cc_mqttsn::message::Willtopicupd<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 28 /* 0x1c */:
    {
        using MsgType = cc_mqttsn::message::Willmsgupd<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    case 254 /* 0xfe */:
    {
        using MsgType = cc_mqttsn::message::Fwd<InterfaceType, TProtOptions>;
        return handler.handle(static_cast<MsgType&>(msg));
    }
    default:
        break;
    };

    return handler.handle(msg);
}

/// @brief Dispatch message object to its appropriate handling function.
/// @details Same as other dispatchGwServerInputMessage(), but receives extra @b idx parameter.
/// @tparam TProtOptions Protocol options struct used for the application,
///     like @ref cc_mqttsn::options::DefaultOptions.
/// @param[in] id Numeric message ID.
/// @param[in] idx Index of the message among messages with the same ID.
///     Expected to be @b 0.
/// @param[in] msg Message object held by reference to its interface class.
/// @param[in] handler Reference to handling object.
/// @see dispatchGwServerInputMessage()
/// @note Defined in cc_mqttsn/dispatch/DispatchGwServerInputMessage.h
template<typename TProtOptions, typename TId, typename TMsg, typename THandler>
auto dispatchGwServerInputMessage(
    TId id,
    std::size_t idx,
    TMsg& msg,
    THandler& handler) -> decltype(handler.handle(msg))
{
    if (idx != 0U) {
        return handler.handle(msg);
    }
    return dispatchGwServerInputMessage<TProtOptions>(id, msg, handler);
}

/// @brief Dispatch message object to its appropriate handling function.
/// @details Same as other dispatchGwServerInputMessage(), but passing
///     cc_mqttsn::options::DefaultOptions as first template parameter.
/// @param[in] id Numeric message ID.
/// @param[in] msg Message object held by reference to its interface class.
/// @param[in] handler Reference to handling object.
/// @see dispatchGwServerInputMessage()
/// @note Defined in cc_mqttsn/dispatch/DispatchGwServerInputMessage.h
template<typename TId, typename TMsg, typename THandler>
auto dispatchGwServerInputMessageDefaultOptions(
    TId id,
    TMsg& msg,
    THandler& handler) -> decltype(handler.handle(msg))
{
    return dispatchGwServerInputMessage<cc_mqttsn::options::DefaultOptions>(id, msg, handler);
}

/// @brief Dispatch message object to its appropriate handling function.
/// @details Same as other dispatchGwServerInputMessageDefaultOptions(), 
///     but receives extra @b idx parameter.
/// @param[in] id Numeric message ID.
/// @param[in] idx Index of the message among messages with the same ID.
/// @param[in] msg Message object held by reference to its interface class.
/// @param[in] handler Reference to handling object.
/// @see dispatchGwServerInputMessageDefaultOptions()
/// @note Defined in cc_mqttsn/dispatch/DispatchGwServerInputMessage.h
template<typename TId, typename TMsg, typename THandler>
auto dispatchGwServerInputMessageDefaultOptions(
    TId id,
    std::size_t idx,
    TMsg& msg,
    THandler& handler) -> decltype(handler.handle(msg))
{
    return dispatchGwServerInputMessage<cc_mqttsn::options::DefaultOptions>(id, idx, msg, handler);
}

/// @brief Message dispatcher class to be used with
///     @b comms::processAllWithDispatchViaDispatcher() function (or similar).
/// @tparam TProtOptions Protocol options struct used for the application,
///     like @ref cc_mqttsn::options::DefaultOptions.
/// @headerfile cc_mqttsn/dispatch/DispatchGwServerInputMessage.h
template <typename TProtOptions = cc_mqttsn::options::DefaultOptions>
struct GwServerInputMsgDispatcher
{
    /// @brief Class detection tag
    using MsgDispatcherTag = void;

    /// @brief Dispatch message to its handler.
    /// @details Uses appropriate @ref dispatchGwServerInputMessage() function.
    /// @param[in] id ID of the message.
    /// @param[in] idx Index (or offset) of the message among those having the same numeric ID.
    /// @param[in] msg Reference to message object.
    /// @param[in] handler Reference to handler object.
    /// @return What the @ref dispatchGwServerInputMessage() function returns.
    template <typename TId, typename TMsg, typename THandler>
    static auto dispatch(TId id, std::size_t idx, TMsg& msg, THandler& handler) ->
        decltype(cc_mqttsn::dispatch::dispatchGwServerInputMessage<TProtOptions>(id, idx, msg, handler))
    {
        return cc_mqttsn::dispatch::dispatchGwServerInputMessage<TProtOptions>(id, idx, msg, handler);
    }

    /// @brief Complementary dispatch function.
    /// @details Same as other dispatch without @b TAllMessages template parameter,
    ///     used by  @b comms::processAllWithDispatchViaDispatcher().
    template <typename TAllMessages, typename TId, typename TMsg, typename THandler>
    static auto dispatch(TId id, std::size_t idx, TMsg& msg, THandler& handler) ->
        decltype(dispatch(id, idx, msg, handler))
    {
        return dispatch(id, idx, msg, handler);
    }

    /// @brief Dispatch message to its handler.
    /// @details Uses appropriate @ref dispatchGwServerInputMessage() function.
    /// @param[in] id ID of the message.
    /// @param[in] msg Reference to message object.
    /// @param[in] handler Reference to handler object.
    /// @return What the @ref dispatchGwServerInputMessage() function returns.
    template <typename TId, typename TMsg, typename THandler>
    static auto dispatch(TId id, TMsg& msg, THandler& handler) ->
        decltype(cc_mqttsn::dispatch::dispatchGwServerInputMessage<TProtOptions>(id, msg, handler))
    {
        return cc_mqttsn::dispatch::dispatchGwServerInputMessage<TProtOptions>(id, msg, handler);
    }

    /// @brief Complementary dispatch function.
    /// @details Same as other dispatch without @b TAllMessages template parameter,
    ///     used by  @b comms::processAllWithDispatchViaDispatcher().
    template <typename TAllMessages, typename TId, typename TMsg, typename THandler>
    static auto dispatch(TId id, TMsg& msg, THandler& handler) ->
        decltype(dispatch(id, msg, handler))
    {
        return dispatch(id, msg, handler);
    }
};

/// @brief Message dispatcher class to be used with
///     @b comms::processAllWithDispatchViaDispatcher() function (or similar).
/// @details Same as GwServerInputMsgDispatcher, but passing
///     @ref cc_mqttsn::options::DefaultOptions as template parameter.
/// @note Defined in cc_mqttsn/dispatch/DispatchGwServerInputMessage.h
using GwServerInputMsgDispatcherDefaultOptions =
    GwServerInputMsgDispatcher<>;

} // namespace dispatch

} // namespace cc_mqttsn
